version: '3'

services:
  web: 
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000" 
    container_name: codesnippets
    volumes: 
      - .:/codesnippets
    ports: 
      - "8000:8000"  