# Generated by Django 3.1.3 on 2021-02-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_codesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
