# Generated by Django 3.1.3 on 2021-02-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_codesnippet_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippetLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('codesnippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.codesnippet')),
            ],
        ),
    ]
